src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <description>This is an individual account, which represents a person.</description>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <recordTypes>
        <fullName>MonTrack</fullName>
        <active>true</active>
        <label>MonTrack</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Cohort__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for MonTRACK functionality; captures the cohort to which a student belongs</description>
        <label>Cohort</label>
        <referenceTo>Cohort__c</referenceTo>
        <relationshipLabel>Campaign Members</relationshipLabel>
        <relationshipName>Campaign_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SSA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for MonTRACK functionality; SSA is the Student Success Advisor who calls the student in the MonTRACK program.</description>
        <label>SSA</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaign_Members</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>when populated, at insert CaseServices logic will attempt to set RecordTypeId to the Id of the Case Record Type Name stored on this field. Exists to assist with external web to form submits to Service queues</description>
        <label>Case Record Type to set</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>used to store linked course code when managing enquiry</description>
        <label>Course Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Course__c.Original_ID__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Linked Enquiries</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Cohort__c.object
<CustomObject>
    <description>Describes a group of students within MonTRACK context.</description>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Applicant_Email_Address__c</fullName>
        <description>populated by bulk api loading process</description>
        <externalId>true</externalId>
        <label>Applicant Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Captures the course code that a student is pursuing</description>
        <label>Course Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MonTrack_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if a student has opted out of MonTRACK</description>
        <label>MonTrack Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monash_Email_Address__c</fullName>
        <description>used to store Contact&apos;s monash assigned email address</description>
        <externalId>true</externalId>
        <label>Monash Email Address</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>A contact that has a Monash identifier, like a Student Id or Applicant Id</description>
        <label>Known to Monash systems</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <description>used to store data about Monash offerings</description>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Used to force uniqueness on course code. Updated from workflow.</description>
        <externalId>true</externalId>
        <label>Course Code Unique</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Course_Description__c</fullName>
        <externalId>true</externalId>
        <label>Course Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Specialisation__c</fullName>
        <externalId>true</externalId>
        <label>Specialisation</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Round__c.object
<CustomObject>
    <description>This object is used to capture the detail of a MonTRACK call round</description>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links to the related campaign</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Rounds</relationshipLabel>
        <relationshipName>Rounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cohort__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Links to the related cohort</description>
        <label>Cohort</label>
        <referenceTo>Cohort__c</referenceTo>
        <relationshipLabel>Rounds</relationshipLabel>
        <relationshipName>Rounds</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Round_Number__c</fullName>
        <description>Indicates the round number</description>
        <label>Round Number</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Round</label>
    <nameField>
        <displayFormat>RND-{00000}</displayFormat>
        <label>Round Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>MonTrack</fullName>
        <active>true</active>
        <label>MonTrack</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Topic__c.object
<CustomObject>
    <description>This object captures the various topics that could be discussed during a MonTRACK call</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Captures a range of topics that can be discussed. It depends on the type of topic selected</description>
        <label>Description</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>No topic discussed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Attendance (lectures, tutorials, labs etc.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - English Proficiency spoken or written</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Essay, report and assignment writing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Exam anxiety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Exam preparation/revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Exam timetable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Exam venue/transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Lecturer/tutor issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Referencing and citing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Results</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Special consideration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Timetable issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Workload/time management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Encumbrance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Enrolment queries/difficulties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Financial issues/difficulties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Moodle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Orientation will miss/has missed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Parking on campus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Parking permits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Scholarships/bursaries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Semester dates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administratoin - IT issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course - Career</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course - Change load</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course – Choice/preference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course - Credit/RPL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course - Exchange/Abroad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Round__c</fullName>
        <description>Identifies the related call round</description>
        <label>Round</label>
        <referenceTo>Round__c</referenceTo>
        <relationshipLabel>Transition Topics</relationshipLabel>
        <relationshipName>Transition_Topics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>SSA_Identified__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the SSA</description>
        <label>SSA Identified</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Transition_Topics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the student/contact</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transition Topics</relationshipLabel>
        <relationshipName>Transition_Topics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Captures the type of topic</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montrack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Campaign (Not Montrack) 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Campaign (Not Montrack) 2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transition Topic</label>
    <nameField>
        <displayFormat>TT-{00000}</displayFormat>
        <label>Transition Topic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transition Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TriggerMuteRequest__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to register per user trigger muting requests. Done using custom settings to avoid DML request if was stored on user record.</description>
    <fields>
        <fullName>TriggersList__c</fullName>
        <description>List of trigger names that are to be muted for this user, separated by commas</description>
        <inlineHelpText>List of trigger names that are to be muted for this user, separated by commas</inlineHelpText>
        <label>Trigger(s) List</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Trigger Mute Request</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>SSA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for MonTRACK functionality, SSA is a Student Success Advisor.</description>
        <label>SSA</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestHelper.cls
/**
 *	Utility class that provides test data creation methods
 * @author PwC
 */

public with sharing class TestHelper {
    
    
    /**
    * apply named permission sets to user supplied, names concatenated with ;
    * @param names names of permission sets, concatenated using semi-colon
    * @param usr the id of the user to apply the permissions to
    * @return void
    */
    public static void applyPermissionSets(String names, user usr){
        Set<string> psNames = new Set<string>();
        for(string nm : names.split(';')) psNames.add(nm);
        List<PermissionSetAssignment> psaList = new List<PermissionSetAssignment>();
        for(PermissionSet ps : [select id from PermissionSet where name in:psNames]){
            psaList.add(new PermissionSetAssignment(PermissionSetId = ps.id, AssigneeId = usr.id));
        }
        insert psaList;
    }
    
    /**
     * generate a list of emailmessage records
     * @param EmailMessage number of email messages to create
     * @param parentId the id of object to parent the messages
     * @param fromName the string containing 'from' for the email message
     * @param fromAddress the string containing from email address for the message
     * @param ToAddress the address that the email message is to be sent to
     * @return list of emailmessage records
     */ 
    public static list<EmailMessage> createEmailMessages(integer EmailMessage, 
                                                 id parentId, 
                                                 String fromName, String fromAddress, 
                                                 String ToAddress){
        list<EmailMessage> emails = new list<EmailMessage>();
        for(integer index=0; index < EmailMessage; index++){
            emails.add(new EmailMessage( subject = 'test email',
                                		parentId = parentId,
                                        textBody = 'test email body',
                                        htmlBody = '<p>test email body</p>',
                                        fromName = fromName,
                                        fromAddress = fromAddress,
                                        toAddress = ToAddress,
                                        MessageDate = Date.today().addDays(-10 * index)
                                        ));
        }
        return emails;
    }
    
    
    /**
    * generate a list of task records
    * @param numberOfTasks the number of task records to create
    * @param whoId the id of the contact to link the tasks to
    * @param whatId the id of another object to link the tasks to
    * @return list of task records
    */ 
    public static list<task> createTasks(integer numberOfTasks, id whoId, id whatId){
        list<task> tasks = new list<task>();
        for(integer index=0; index < numberOfTasks; index++){
            tasks.add(new Task( subject = 'test task',
                                activitydate = Date.today().addDays(-60).addDays(index),
                                description = 'test description',
                                whoId = whoId,
                                whatId = whatId,
                                Status = 'Completed',
                               Type = 'Other'));
        }
        return tasks;
    }
    
    /**
    * generate a list of attachments
    * @param numberOfAttachments the number of attachment records to create
    * @param parentId the id of the parent object for the attachments
    * @return list of attachment records
    */ 
    public static list<attachment> createAttachments(integer numberOfAttachments, id parentId){
        list<attachment> attachments = new list<attachment>();
        for(integer index=0; index<numberOfAttachments; index++){
            attachments.add(new attachment(name = 'att_'+String.valueOf(index),
                                           parentId = parentId,
                                           body = Blob.valueOf('testAttachment')));
        }
        return attachments;
    }
    
    /**
    * generate a list of course records
    * @param numberOfCourses the number of course__c records to setup
    * @return a list of course__c records
    */ 
    public static list<Course__c> createCourses(integer numberOfCourses){
        list<course__c> courses = new list<course__c>();
        for(integer index=0; index<numberOfCourses; index++){
            courses.add(new course__c(name = String.valueOf(index), 
                                      course_description__c = 'test course',
                                      specialisation__c = String.valueOf(index)+'specialty'));
        }
        return courses;
    }
    
    
    /**
    * generate test contact records that have no parent account record, so automation
    * will create the account records for them.
    * @param numberOfContacts the number of contact records to setup
    * @return list of contact records with no account id
    */
	    public static list<Contact> createOrphanContactRecords(integer numberOfContacts){
	    	return createStudentContacts(numberOfContacts,null);
	    }
    
    
    
    /**
    * ? redundant logic to generate PAs
    * <p>Can likely be factored out of logic layer altogether, once solution stable
    * @param numberOfStudents the number of student records to setup
    * @return list of account records that ? represent person accounts
    */
	    public static list<Account> createStudent(integer numberOfStudents){
	        
	        list<Account>  accounts = new  list<Account>();
	        Schema.DescribeSObjectResult descSobject =Account.SObjectType.getDescribe();
	        
	        Map<String,Schema.RecordTypeInfo> recordTypeInfoByName = descSobject.getRecordTypeInfosByName();
	        
	        Id recTypeID = recordTypeInfoByName.get('Individual').getRecordTypeId();
	        
	        // ? need an assert in here to confirm we get the record type, given its hardcoded ?
	        // need to refactor hardcoded string values over to helper/service classes
	        
	        for(integer studentNumber = 0; studentNumber < numberOfStudents; studentNumber++){
	            Account newAccount= new Account( 
	                                         Name='Account'+studentNumber,                                         
	                                         recordtypeid=recTypeID
	                                         );
	                accounts.add(newAccount);
	        }
	        return accounts;       
	    }
    
    
    /**
    * retrieve the test contact records
    * @return the contact records that have been inserted during test setup
    */
    	public static list<Contact> retrieveContactRecords(){
    		
    		return new list<Contact>([select id,
											firstName,
											lastName,
											Email,
											Monash_Email_Address__c,
											Applicant_Email_Address__c
											from Contact limit 500]);
    	}
    
    
    /**
    * builds a list of student contact records - ? redundant logic from the original UniCRM v1.
    * @param numberOfContacts the number of records to setup
    * @param accounts a list of accounts that student records are to be setup for on a 1:1 basis
    * @return list of contact records each having a parent account id prior to insert
    */
	    public static list<Contact> createStudentContacts(integer numberOfContacts, List<Account> accounts){
	       
	        list<Contact> newContacts = new  list<Contact>();
	        for(integer contactNumber =0; contactNumber < numberOfContacts; contactNumber++){
	            Id accountId = (accounts == null) ? null : accounts[contactNumber].Id;
	            Contact newContact= new contact( 
	                                         FirstName='Cruz'+ contactNumber,
	                                         LastName='John',                                         
	                                         AccountId= accountId,
	                                         MonTrack_Opt_Out__c=false,
	                                         Email = String.valueOf(contactNumber) + 'testemailAddress@monash.edu',
	                                         Monash_Email_Address__c = String.valueOf(contactNumber) + 'monashstudenttest@monash.edu',
	                                         Applicant_Email_Address__c = String.valueOf(contactNumber) + 'personaldomaintest@monash.edu'
	                                         );
	                                     
	                newContacts.add(newContact);
	        }
	        return newContacts;
	    }
    
    
    /**
    * creates a specific type of user (SSA) for Montrack testing purposes
    * @return a user record that has the SSA custom field set to true
    */
	    public static User ssaUser(){
	        	
        	User ssaUser = createTestUsers('System Administrator',1)[0];
        	ssaUser.SSA__c = true;
        	update ssaUser;
	        	
	        return ssaUser;
	    
	    }
    
    
    /**
    * create a list of campaign records for testing
    * @param numberOfCampaigns the number of campaign records to setup
    * @return a list of campaign records
    */
	    public static list<Campaign> createCampaign(integer numberOfCampaigns){
	        list<Campaign> newCampaigns = new list<Campaign>();
	        for(integer campaignNumber = 0; campaignNumber < numberOfCampaigns; campaignNumber++){
	            Campaign newCampaign = new Campaign(Name='My Campaign ' + campaignNumber);
	            newCampaigns.add(newCampaign);
	        }
	        return newCampaigns;
	    
	    }
    
    
    /**
    * creates a list of cohort records for testing
    * @param numberOfCohorts the number of cohort records to setup
    * @return a list of cohort records
    */
	    public static list<Cohort__c> createCohort(integer numberOfCohorts){
	        list<Cohort__c> newCohorts = new list<Cohort__c>();
	        for(integer cohortNumber = 0; cohortNumber < numberOfCohorts; cohortNumber++){
	            Cohort__c newCohort = new Cohort__c(Name='2014-1' + cohortNumber);
	            newCohorts.add(newCohort);
	        }
	        return newCohorts;
	    
	    }
	 
	    
    /**
    *	creates campaign member records that map to a specific cohort and ssa for testing
	* @param ssaID the Id of an existing SSA user
	* @param cohortID the Id of an existing cohort record
	* @param CampaignID the Id of an existing campaign record
	* @param contactIds a set of contact ids of existing records that need to be linked to cohort etc for testing
	* @return a list of campaign member records setup to support MonTrack testing
    */
	    public static list<CampaignMember> createCampaignMember(ID ssaID, 
	                                                            ID cohortID, 
	                                                            ID CampaignID,
	                                                            Set<ID> contactIds){
	        
	        list<CampaignMember> newCampaignMembers = new list<CampaignMember>();
	        for(ID contactId:contactIds){
	            CampaignMember newCampaignMember = new CampaignMember(Cohort__c=cohortID,
					                                                  SSA__c=ssaID,
					                                                  CampaignID=CampaignID,
					                                                  ContactID=contactId);
	                        newCampaignMembers.add(newCampaignMember);
	        }
	        return newCampaignMembers;
	    }
    
    
    /**
    *	create a list of round records for testing MonTrack functionality
	* @param cohortId the id of an existing cohort to link the round to
	* @param CampaignID the id of an existing campaign to link the round to
	* @param ctr the number of rounds to setup
	* @return a list of round records all linked to cohort,campaign etc as required
    */
	    public static list<Round__c> createRounds(ID cohortID, 
	                                              ID CampaignID,
	                                              Integer ctr){
	        
	        List<Round__c> newRounds = new list<Round__c>();
	        for(Integer i=0;i<ctr;i++){
	            Round__c newRound= new Round__c(Campaign__c=CampaignID,
	                                     		Cohort__c=cohortID,
	                                     		Round_Number__c=String.valueof(i+1) );
	            
	            newRounds.add(newRound);   
	        
	        }                                         
	        return newRounds;                                             
	                                              
	    }
    
    
    /**
    *  create topics records for testing purposes
    *  @param roundId the id of an existing round record to link to
    *  @param SSAId the id of an existing SSA user to link to 
    *  @param contactId the id of a Montrack test contact record
    *  @param numberOfTopics the number of topic records to return
    *  @return a list of topic records all linked as required for Montrack testing
    */
	    public static list<Topic__c> createTopics(ID roundID,
	                                            ID SSAID,
	                                            ID contactID,
	                                            Integer numberOfTopics){
	        list<Topic__c> topics = new List<Topic__c>();
	        for(Integer topicNumber =0; topicNumber < numberOfTopics; topicNumber++){
	            Topic__c newTopic= new Topic__c(Round__c=roundID, 
	                                            SSA_Identified__c=SSAID, 
	                                            Type__c='General', 
	                                            Description__c='Other',
	                                            Student__c=contactID);
	            topics.add(newTopic);
	        }       
	        return topics;                             
	    }


	/**
    * insert a custom setting record used to mute a trigger
    * @param username the name of user to insert trigger mute setting for
    * @param triggerString a string of triggers to be muted, concatenated via ','
    */
	    public static void createTriggerMutingCustomSetting(String username, String triggersString){
	    	TriggerMuteRequest__c request = new TriggerMuteRequest__c(Name = username,
	    															  TriggersList__c = triggersString);
	    	insert request;														  
	    }
	    
    
    /**
    /* setup Test user data
     * @param profileName a string containing the profile to use for the new users
     * @param numberOfusers the number of user records to setup
     * @return a list of user records that have been inserted, so have ids ready for use
    */ 
	    public static List<User> createTestUsers( String profileName , integer numberOfUsers){
	        Id profileId = [select id from Profile where name =:profileName limit 1].Id;
	        system.assertNotEquals(null,profileId,'No user profile found for user setup');
	        
	        List<User> users = new List<User>();
	        
	        for(Integer userCount = 0; userCount < numberOfUsers; userCount++){
		        Integer rnd = Integer.valueOf(Math.random()*9999);
		        users.add(new User(Alias = String.valueOf(rnd)+ 'usr', 
		                        Email= String.valueOf(rnd) +'testuser@monash.edu', 
		            			EmailEncodingKey='UTF-8', 
		                        LastName='TestingUser', 
		                        LanguageLocaleKey='en_US', 
		            			LocaleSidKey='en_GB', 
		                        ProfileId = profileId, 
		            			TimeZoneSidKey='Australia/Sydney', 
		                        UserName= String.valueOf(rnd) +'testuser@monash.edu'));
	        }
	        insert users;
	        return users;
	    }
	
	
	/**
	* static map of simulated errors to throw during testing
	* <p>if dev wants to simulate errors in testing, then can incorporate this logic into codebase.
	* @return a set of custom error types described as strings.
	*/
		private static Set<string> errorsToThrow {
			get{
				if(errorsToThrow == null) errorsToThrow = new Set<string>();
				return errorsToThrow;
			}
			private set;
		}
	
	/**
	* store an error simulation request
	* @param errorType the name of the error that dev wants to test
	* @ return void
	*/
		public static void setupError(String errorType){
			errorsToThrow.add(errorType);
		}
	
	/**
	* confirm if error simulation should go ahead or not
	* @param errorType string value for dev custom error that is to be checked for
	* @return boolean of true if error is to be thrown, otherwise false
	*/
		public static Boolean throwError(String errorType){
			if(Test.isRunningTest() && errorsToThrow.contains(errorType)){
				errorsToThrow.remove(errorType); // only permit error to fire once per time it is set
				return true;
			} else {
				return false;
			}
		}
	
	/**
	* create a list of simple web to case forms
	* @param numberOfForms the number of web form cases to setup
	* @return a list of case records
	*/
		public static List<Case> webToCaseForms(Integer numberOfForms){
			
			List<Case> cases = new List<Case>();
			
			for(integer formNumber = 0; formNumber < numberOfForms ; formNumber++){
				cases.add(new Case( SuppliedName = 'testName',
									SuppliedPhone = '0400000000',
									SuppliedEmail = String.valueOf(formNumber) + 'testformEmail@monash.edu',
									Type = 'Web',
									Case_type__c = '',
									ContactId = null,
									AccountId = null,
                                    Course_code__c = '0'));
			}
			
			return cases;
		}
	
	
		
}