src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <description>This is an individual account, which represents a person.</description>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Supplied_Country_of_Residence__c</fullName>
        <description>populated via web form, copied to Contact</description>
        <label>Country of Residence</label>
        <picklist>
            <picklistValues>
                <fullName>ADELIE LAND (FRANCE)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFGHANISTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALBANIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALGERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANDORRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGOLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTARCTICA, NFD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARGENTINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARGENTINIAN ANTARCTIC TERRITORY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARMENIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIAN ANTARCTIC TERRITORY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIAN EXTERNAL TERRITORIES, NEC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZERBAIJAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHAMAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHRAIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BANGLADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BARBADOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELARUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELGIUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELIZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BENIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BERMUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHUTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOLIVIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOTSWANA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAZIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRITISH ANTARCTIC TERRITORY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supplied_Email_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Mapped to Contact on webform submit</description>
        <label>Supplied Email Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Applicant_Email_Address__c</fullName>
        <description>populated by bulk api loading process</description>
        <externalId>true</externalId>
        <label>Applicant Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Country_of_Residence__c</fullName>
        <description>Captures a student&apos;s country of residence</description>
        <label>Country of Residence</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADELIE LAND (FRANCE)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFGHANISTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALBANIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALGERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANDORRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGOLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTARCTICA, NFD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARGENTINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARGENTINIAN ANTARCTIC TERRITORY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARMENIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIAN ANTARCTIC TERRITORY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIAN EXTERNAL TERRITORIES, NEC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZERBAIJAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHAMAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHRAIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BANGLADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BARBADOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELARUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELGIUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELIZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BENIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BERMUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHUTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOLIVIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOTSWANA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAZIL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email_Addresses__c</fullName>
        <description>used to store concatenated email addresses that this contact has had over time</description>
        <label>Email Addresses Used</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MonTrack_Opt_Out_Reason__c</fullName>
        <description>Captures the reason for a student opting out of MonTRACK</description>
        <label>MonTrack Opt Out Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feeling Confident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Has Sibling/s at University</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Has Studied Previously</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Has Taken Intermission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Reason</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MonTrack_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if a student has opted out of MonTRACK</description>
        <label>MonTrack Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monash_Email_Address__c</fullName>
        <description>used to store Contact&apos;s monash assigned email address</description>
        <externalId>true</externalId>
        <label>Monash Email Address</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Exception_Log__c.object
<CustomObject>
    <description>This object captures the exceptions related to the code</description>
    <fields>
        <fullName>Function_Name__c</fullName>
        <description>Used for backend logic to track exceptions to expected behaviour in UniCRM</description>
        <label>Function Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>ERR-{00000000}</displayFormat>
        <label>Exception Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ContactServices_Test.cls
/**
 * This class contains unit tests for validating the behavior of ContactServices methods
 * these methods are part of the testing framework implemented throughout UniCRM
 * 
 */
 
@isTest
private class ContactServices_Test {

    
    static testMethod void checkFieldMappingLogic(){
        list<Contact> testContacts = TestHelper.createOrphanContactRecords(1);
        testContacts[0].HasOptedOutOfEmail = false;
        testContacts[0].Country_of_Residence__c = 'AU';
        insert testContacts;
        system.assertNotEquals(null, testContacts[0].id,'contacts didnt insert as expected');
        
        // now create a case with mappings to pass to contact
        // 
        case c = new case(contactId = testContacts[0].id,
                          supplied_Email_Opt_out__c = true,
                          Supplied_Country_of_Residence__c = 'NZ');
        ContactServices.copyMappedFieldsToCaseContacts(new list<case>{ c });
        
        contact contactResult = [select id,HasOptedOutOfEmail,Country_of_Residence__c from contact where id =:testContacts[0].id limit 1];
        
        
    }
    
    
    static testMethod void testMontrackMethods(){
        
        list<Contact> testContacts = TestHelper.createOrphanContactRecords(1);
        insert testContacts;
        system.assertNotEquals(null, testContacts[0].id,'contacts didnt insert as expected');
        
        testContacts[0].MonTrack_Opt_Out__c = true;
        testContacts[0].MonTrack_Opt_Out_Reason__c = 'testing';
        ContactServices.updateMontrackFields(testContacts[0]);
        
        system.assertEquals('testing', 
                            [select id, MonTrack_Opt_Out_Reason__c from Contact where id =:testContacts[0].id].MonTrack_Opt_Out_Reason__c,
                            'contact didnt update as expected');
        
    }
    
    
    /**
    * confirm that on new contact insertion, if no account provided a new Individual Account is established
    * test bulk insert including duplicate contact names
    * test deletion performs cleanup
    */
    static testMethod void basicIndividualInsertionAndDeletion() {
        
        list<Contact> testContacts = TestHelper.createOrphanContactRecords(300);
        
        Test.startTest();
        
        insert testContacts;
        
        system.assertEquals(testContacts.size(),
                            [select COUNT() from Account where RecordTypeId =:CommonServices.RecordTypeId('Account',AccountServices.ACCOUNT_INDIVIDUAL_TYPE)],
                            'incorrect number of accounts with rtype individual created');
        
        
        delete TestContacts;
        
        system.assertEquals(0,
                            [select COUNT() from Account where RecordTypeId =:CommonServices.RecordTypeId('Account',AccountServices.ACCOUNT_INDIVIDUAL_TYPE)],
                            'incorrect number of accounts with rtype individual remain after deletion');
        
        Test.stopTest();
    }
    
    
    static testMethod void basicUpdate() {
        
        list<Contact> testContacts = TestHelper.createOrphanContactRecords(300);
        
        Test.startTest();
        
        insert testContacts;
        
        system.assertEquals(testContacts.size(),
                            [select COUNT() from Account where RecordTypeId =:CommonServices.RecordTypeId('Account',AccountServices.ACCOUNT_INDIVIDUAL_TYPE)],
                            'incorrect number of accounts with rtype individual created');
        
        for(integer i=0; i<testContacts.size(); i++){
            testContacts[i].firstname = 'different';
            testContacts[i].lastname ='test';
        }
        update testContacts;
        
        Test.stopTest();
        
        system.assertEquals(testContacts.size(),
                            [select COUNT() from Account where name = 'different test' ],
                            'incorrect update of account name');
        
        
    }
    
    
    /**
    * confirm that on new contact insertion, if error during insertion error handled correctly.
    * test bulk insert including duplicate contact names
    * test deletion handles error correctly
    */
    static testMethod void basicIndividualInsertionAndDeletionErrorHandling() {
        
        list<Contact> testContacts = TestHelper.createOrphanContactRecords(300);
        
        TestHelper.setupError('accountInsert'); // induces a one off error condition within the logic being tested
        
        Test.startTest();
        
        Database.SaveResult[] saveResults = Database.insert(TestContacts, false); // provide for partial inserts in bulk
        
        system.assertEquals(testContacts.size()-1,
                            [select COUNT() from Contact],
                            'incorrect number of contacts inserted');
            
        system.assertEquals(testContacts.size() - 1,
                            [select COUNT() from Account where RecordTypeId =:CommonServices.RecordTypeId('Account',AccountServices.ACCOUNT_INDIVIDUAL_TYPE)],
                            'incorrect number of accounts with rtype individual created');
        
        TestHelper.setupError('accountDelete'); // induces a one off error condition within the logic being tested
        system.assertEquals(true,TestHelper.throwError('accountDelete'));
        system.assertEquals(false,TestHelper.throwError('accountDelete'));
        TestHelper.setupError('accountDelete');
        
        List<Contact> contactsToDelete = new List<Contact>([select id from Contact]); // refresh list for next test
        delete contactsToDelete;
        
        system.assertEquals(1,
                            [select COUNT() from Exception_Log__c where Function_Name__c = 'ContactServices.cleanUpOrphanAccounts'],
                            'no error logged to Exception logs');
        
        Test.stopTest();
    }
    
    static testMethod void verifyMultipleEmailAddressBehaviour(){
        
        list<Contact> testContacts = TestHelper.createOrphanContactRecords(1);
        
        // prep for test use cases
        for(Contact testRecord : testContacts){
            testRecord.Applicant_Email_Address__c = '';
            testRecord.Monash_Email_Address__c = '';
        }
        
        Test.startTest();
        insert testContacts;
        
        
        
                            
        testContacts = TestHelper.retrieveContactRecords(); // pull in the updated records for further testing
        
        for(integer recCount = 0; recCount < testContacts.size(); recCount++) 
            testContacts[recCount].Email = String.valueOf(recCount) + 'nonmonash@somedomain.com.au';
            
        update testContacts;
        
        for(contact c : [select id,Email_Addresses__c from Contact])
            system.assert(c.Email_Addresses__c != null,
                            'expected all contact records to have email address history field set');
        
        
        
        
        
                
        // test deletion of contacts - should also have accounts removed
        
        Set<id> accountIds = new Set<Id>();
        for(contact c : testContacts) accountIds.add(c.accountId);
        delete testContacts;
        system.assertEquals(0,
                            [select count() from Account where id in:accountIds],
                            'should not be any accounts left');
        
        Test.stopTest();
    }
    
    
}