src/objects/Campaign.object
<CustomObject>
    <recordTypes>
        <fullName>MonTrack</fullName>
        <active>true</active>
        <label>MonTrack</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Cohort__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for MonTRACK functionality; captures the cohort to which a student belongs</description>
        <label>Cohort</label>
        <referenceTo>Cohort__c</referenceTo>
        <relationshipLabel>Campaign Members</relationshipLabel>
        <relationshipName>Campaign_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SSA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for MonTRACK functionality; SSA is the Student Success Advisor who calls the student in the MonTRACK program.</description>
        <label>SSA</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaign_Members</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Cohort__c.object
<CustomObject>
    <description>Describes a group of students within MonTRACK context.</description>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MonTrack_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if a student has opted out of MonTRACK</description>
        <label>MonTrack Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Round__c.object
<CustomObject>
    <description>This object is used to capture the detail of a MonTRACK call round</description>
    <fields>
        <fullName>Cohort__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Links to the related cohort</description>
        <label>Cohort</label>
        <referenceTo>Cohort__c</referenceTo>
        <relationshipLabel>Rounds</relationshipLabel>
        <relationshipName>Rounds</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Round_Number__c</fullName>
        <description>Indicates the round number</description>
        <label>Round Number</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Round</label>
    <nameField>
        <displayFormat>RND-{00000}</displayFormat>
        <label>Round Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>MonTrack</fullName>
        <active>true</active>
        <label>MonTrack</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/mt_createTaskBatch.cls
/**
 * called from the RoundServices.class
 * purpose is to generate Montrack related tasks for a cohort of Campaign Members when a Round record is
 * created.
 * @author PwC
 */


global  class mt_createTaskBatch implements Database.Batchable<sObject> {
    
    global final String Query; // used to define scope of batch job
    global  String RoundNumber; // used in email post batch completion
    global  String RoundName; // used in email post batch completion
    global Boolean errorOccured;
    
    global Set<ID> cohortID = new set<ID>();
    global map<ID, Round__c> rMap= new map<ID, Round__c>();
    
    global mt_createTaskBatch(list<Round__c> roundList){ 
    	
    	// constructor builds map for use in query scope
        
        Set<Id> roundIds = new Set<Id>();
        for(Round__c round : roundList) roundIds.add(round.id);
        
        // retrieve cohort details not passed in 
        
        for(Round__c round:[ select id, 
        							Round_Number__c, 
        							Cohort__r.Name, 
        							Cohort__c,
        							Name from Round__c where id in:roundIds]){
            rMap.put(round.Cohort__c, round);
            RoundNumber=round.Round_Number__c;
            RoundName=round.Cohort__r.Name;
        }
        
        cohortID=rMap.keyset();
        
        
        Query='SELECT SSA__c,Cohort__c, ContactId,Contact.MonTrack_Opt_Out__c FROM CampaignMember WHERE Cohort__c IN:cohortID AND Contact.MonTrack_Opt_Out__c=False';       
    	
    	errorOccured = false;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext BC,  List<CampaignMember> scope){
        
        Id recTypeId = CommonServices.recordTypeId('Task',RoundServices.MONTRACK_RECORDTYPE_NAME);
        
        list<Task> tasks= new list<Task>();
        
        for(CampaignMember s : scope){
        
            Task newTask= new Task( whatId=rMap.get(s.Cohort__c).Id, 
                                    whoId=s.contactID,
                                    OwnerId=s.SSA__c,
                                    Subject='MonTRACK Call',recordtypeid=recTypeID);
            tasks.add(newTask);
        }
        
        if(!tasks.isEmpty()){
        	try{
        		insert tasks;
        	} catch (Exception ex){
        		errorOccured = true;
        		ExLog.add('Round insert', 'Task', 'mt_createTaskBatch', ex); // log to stored error logs for review
        	}
        }  
    }
    
    global void finish (Database.BatchableContext BC)
    {
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
        
        mail.setToAddresses(new String[] { UserInfo.getUserEmail() });
        mail.setSenderDisplayName('MonTRACK'); 
        mail.setSubject('Processing for Call Round ' + RoundNumber + ', Cohort '+ RoundName + ' results');  
        if(!errorOccured){
        	mail.setPlainTextBody('You can now access the Call List through the MonTRACK Call List tab.');
        } else {
        	mail.setPlainTextBody('Errors have occured while setting up Montrack tasks, please notify your system administrator. Error logs have been generated for assessment.');
        }
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        
    }

}