src/objects/Campaign.object
<CustomObject>
    <recordTypes>
        <fullName>MonTrack</fullName>
        <active>true</active>
        <label>MonTrack</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Cohort__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for MonTRACK functionality; captures the cohort to which a student belongs</description>
        <label>Cohort</label>
        <referenceTo>Cohort__c</referenceTo>
        <relationshipLabel>Campaign Members</relationshipLabel>
        <relationshipName>Campaign_Members</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Cohort__c.object
<CustomObject>
    <description>Describes a group of students within MonTRACK context.</description>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MonTrack_Opt_Out_Reason__c</fullName>
        <description>Captures the reason for a student opting out of MonTRACK</description>
        <label>MonTrack Opt Out Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feeling Confident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Has Sibling/s at University</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Has Studied Previously</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Has Taken Intermission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Reason</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MonTrack_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if a student has opted out of MonTRACK</description>
        <label>MonTrack Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>A contact that has a Monash identifier, like a Student Id or Applicant Id</description>
        <label>Known to Monash systems</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Referrals__c.object
<CustomObject>
    <description>This objects captures the referrals from a MonTRACK SSA</description>
    <fields>
        <fullName>Referral__c</fullName>
        <description>Captures the organization/service of Monash that a student is referred to from MonTRACK</description>
        <label>Referral</label>
        <picklist>
            <picklistValues>
                <fullName>No Referral given</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chaplains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Childcare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counselling Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disability Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment and Careers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eSolutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty Course Adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty Student Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty Tutor/Lecturer/Unit Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Language and Learning online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Skills Adviser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Library</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monash Abroad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monash Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monash Postgraduate Association (MPA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monash Residential Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monash Sport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Safer Community</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Association</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Rights</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supervisor follow up required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Monash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yulendj Indigenous Engagement Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Round__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the MonTRACK call round</description>
        <label>Round</label>
        <referenceTo>Round__c</referenceTo>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the student who was referred by the SSA</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{00000}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Round__c.object
<CustomObject>
    <description>This object is used to capture the detail of a MonTRACK call round</description>
    <fields>
        <fullName>Cohort__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Links to the related cohort</description>
        <label>Cohort</label>
        <referenceTo>Cohort__c</referenceTo>
        <relationshipLabel>Rounds</relationshipLabel>
        <relationshipName>Rounds</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Round</label>
    <nameField>
        <displayFormat>RND-{00000}</displayFormat>
        <label>Round Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>MonTrack</fullName>
        <active>true</active>
        <label>MonTrack</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Topic__c.object
<CustomObject>
    <description>This object captures the various topics that could be discussed during a MonTRACK call</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Captures a range of topics that can be discussed. It depends on the type of topic selected</description>
        <label>Description</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>No topic discussed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Attendance (lectures, tutorials, labs etc.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - English Proficiency spoken or written</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Essay, report and assignment writing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Exam anxiety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Exam preparation/revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Exam timetable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Exam venue/transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Lecturer/tutor issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Referencing and citing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Results</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Special consideration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Timetable issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic - Workload/time management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Encumbrance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Enrolment queries/difficulties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Financial issues/difficulties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Moodle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Orientation will miss/has missed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Parking on campus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Parking permits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Scholarships/bursaries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration - Semester dates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administratoin - IT issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course - Career</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course - Change load</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course – Choice/preference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course - Credit/RPL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course - Exchange/Abroad</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Round__c</fullName>
        <description>Identifies the related call round</description>
        <label>Round</label>
        <referenceTo>Round__c</referenceTo>
        <relationshipLabel>Transition Topics</relationshipLabel>
        <relationshipName>Transition_Topics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the student/contact</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transition Topics</relationshipLabel>
        <relationshipName>Transition_Topics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Captures the type of topic</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montrack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Campaign (Not Montrack) 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Campaign (Not Montrack) 2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transition Topic</label>
    <nameField>
        <displayFormat>TT-{00000}</displayFormat>
        <label>Transition Topic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transition Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/mt_mainControllerCC_Test.cls
/**
 * This class contains unit tests for validating the behavior of the MonTrack custom controller
 * these methods are part of the testing framework implemented throughout UniCRM
 * 
 */
@isTest
private class mt_mainControllerCC_Test {
    static testMethod void testmt_mainControllerCC() {
        
        //create user
        
        User u= TestHelper.ssaUser();
        
        //create account
        
        List<Account>acct= TestHelper.createStudent(10);
        insert acct;
        
        List<Contact> conList= TestHelper.createStudentContacts(10, acct);
        
        insert conList;
        
        Set<ID>accountID = new Set<ID>();
        
        for(Account a:acct){
            accountID.add(a.ID);
        }
        
        //create Campaign
        
        List<Campaign> camp=  TestHelper.createCampaign(1);
        insert camp;
        
        //create Cohort
        
        List<Cohort__c> cohort = TestHelper.createCohort(2);
        insert cohort;
        
        set<ID> contactID= new Set<ID> ();
        for(Contact con : conList){
            contactID.add(con.Id);
        }
        list<CampaignMember> cm= TestHelper.createCampaignMember(u.Id, cohort[0].id, camp[0].Id,contactID );
        insert cm;
        
        list<CampaignMember> tmpCM= new List<CampaignMember>();
        tmpCM=[SELECT ID,contactID,cohort__c,CampaignID FROM CampaignMember WHERE Cohort__c=:cohort[0].ID AND CampaignID=:camp[0].Id ];
        
        list<Round__c> rList= TestHelper.createRounds(tmpCM[0].Cohort__c, tmpCM[0].CampaignId, 4); 
        insert rList;
        
        
        Set<ID>roundID= new Set<ID>();
        for(Round__c r:rList){
            roundID.add(r.Id);
        }
            
        Test.startTest();
            System.runAs(u){
                // confirming can add tasks
                list<Task> taskList = new list<Task>();
                boolean callbackAdded = false;
                for(ID conID:contactID){
                Task newtask= new Task( whatId= rlist[3].id,
                                     whoId=conID,
                                     Subject='MonTRACK Call');
                                     if(!callbackAdded){
                                        newTask.Status = 'Call Back Requested by Student/Other';
                                        newTask.Call_Back_Date_Time__c = datetime.now().addHours(1);
                                        callbackAdded = true;
                                     }
                    taskList.add(newtask);
                }
                insert taskList;
                List<Task> task=[Select Id, WhatID FROM Task where WhatID =:rlist[3].id];
                
                
         
                 PageReference ref = Page.mt_main;
                 Test.setCurrentPage(ref);
                 mt_mainControllerCC montrack = new mt_mainControllerCC();                 
                 List<selectOption> cOptions = montrack.cohortOptions;
                 montrack.cohort = cohort[0].id;
                 List<selectOption> rOptions = montrack.roundOptions;
                 montrack.round = rList[3].id;
                 List<selectOption> uOptions = montrack.ssaUserOptions;                 
                 montrack.ssaUser = u.id;
                 montrack.retrieveCalls();
                 List<selectOption> fOptions = montrack.filterOptions;
                 montrack.listFilter= 'Not Started';                 
                 montrack.retrieveCalls();
                 montrack.listFilter= 'Incomplete';
                 montrack.retrieveCalls();
                 montrack.listFilter= 'Completed';
                 montrack.retrieveCalls();
                 montrack.listFilter= 'All';
                 montrack.retrieveCalls();
                 
                 string msg = montrack.nextCallbackMessage;                 
                 system.assertEquals(10,montrack.taskDetailList.size());
                 
                 id tskId = montrack.taskDetailList[0].taskId;
                 id conId = montrack.taskDetailList[0].contactId;
                 
                 apexpages.currentpage().getparameters().put('tId',tskId);
                 apexpages.currentpage().getparameters().put('cId',conId);
                 montrack.taskClicked();
                 
                 
                 
                 montrack.saveCall(); //Error                   
                 montrack.currenttask.status = 'Call Back Requested by Student/Other';
                 montrack.saveCall(); //Error
                 montrack.currenttask.status = 'No Answer';
                 montrack.currentContact.MonTrack_Opt_Out__c = true;
                 montrack.saveCall(); //Error
                 
                 montrack.currenttask.status = 'No Answer'; //I
                 montrack.currentTask.Call_Back_Date_Time__c= System.Now(); 
                 montrack.currentContact.MonTrack_Opt_Out__c = true;
                 montrack.currentContact.MonTrack_Opt_Out_Reason__c='Reason';
                 montrack.saveCall();
                 
                 
                                 
                 apexpages.currentpage().getparameters().put('tId',tskId);
                 apexpages.currentpage().getparameters().put('cId',conId);
                 montrack.taskClicked();
                 
                 //montrack.testRoundTasks = montrack.otherRounds; 
                 //montrack.testTaskHistory = montrack.taskHistories;
                 
                 montrack.currenttask.status = 'No Answer'; //II
                 montrack.currentTask.Call_Back_Date_Time__c= System.Now(); 
                 montrack.currentContact.MonTrack_Opt_Out__c = true;
                 montrack.currentContact.MonTrack_Opt_Out_Reason__c='Reason';               
                 montrack.saveCall();
                 
                 montrack.deleteTask();    //undo
                 
                 montrack.currenttask.status = 'No Answer'; //II
                 montrack.currentTask.Call_Back_Date_Time__c= System.Now(); 
                 montrack.currentContact.MonTrack_Opt_Out__c = true;
                 montrack.currentContact.MonTrack_Opt_Out_Reason__c='Reason';               
                 montrack.saveCall();
                 
                 montrack.currenttask.status = 'Completed';                
                 montrack.saveCall(); //Error-Complete your call                 
                 
                                                                
                 //Topic
                 montrack.saveTopicRecord();    //Exception //Both are mandatory                 
                 montrack.topic.type__c = 'Montrack';
                 montrack.saveTopicRecord();    //Exception
                 montrack.topic.description__c = 'Academic - Exam timetable'; 
                 montrack.saveTopicRecord();
                 
                 Id topicId=montrack.topic.id;
                 apexpages.currentPage().getParameters().put('tId',topicId);
                 montrack.deleteTopicRecord();
                 
                 //Referral
                 montrack.saveReferralRecord(); //Exception
                 montrack.referral.referral__c = 'Childcare';
                 montrack.saveReferralRecord();
                 
                 
                 Id referralId=montrack.referral.id;
                 apexpages.currentPage().getParameters().put('rId',referralId);
                 montrack.deleteReferralRecord();
                 
                 montrack.currentTask.Reaction_to_Call__c = '';
                 montrack.currentTask.Duration_mins__c = '';
                 montrack.saveCall(); //Error
                 
                 montrack.currentTask.Reaction_to_Call__c = 'Well Received';
                 montrack.currentTask.Duration_mins__c = '5';
                 montrack.saveCall(); //Save
                 
                 
                 
                 
                 
                 //Topic Insert after Complete
                 montrack.topic.description__c = 'Academic - Exam timetable'; 
                 montrack.topic.type__c = 'Montrack';
                 montrack.saveTopicRecord();    //Error
                 //Referral after complete
                 montrack.referral.referral__c = 'Childcare';
                 montrack.saveReferralRecord();
                 
                 apexpages.currentpage().getparameters().put('tId',tskId);
                 apexpages.currentpage().getparameters().put('cId',conId);
                 montrack.taskClicked();
                 montrack.saveCall(); //Error //Completed Call
                 
                 montrack.deleteId=montrack.currentTask.id;
                 montrack.deleteTask();    //undo  //Exception
                 
                 
                 
                // montrack.clearContextStudent(); // cover off, and going to reset in next step
                 
                 apexpages.currentPage().getParameters().put('rId',referralId);
                 montrack.deleteReferralRecord();
                 
                 
                 
                 
                 montrack.resetChildObjects();
                 montrack.revertToListView();
                 montrack.dummyAction();
                 
                             
            }
        Test.stopTest();        
    }           
    static testMethod void throughToCompleteScenario() {
        //create user
        User u= TestHelper.ssaUser();
        //create account
        List<Account>acct= TestHelper.createStudent(10);
        insert acct;
        List<Contact> conList= TestHelper.createStudentContacts(10, acct);
        insert conList;
        Set<ID>accountID = new Set<ID>();
        for(Account a:acct){
            accountID.add(a.ID);
        }
        //create Campaign
        List<Campaign> camp=  TestHelper.createCampaign(1);
        insert camp;
        //create Cohort
        List<Cohort__c> cohort = TestHelper.createCohort(2);
        insert cohort;
        set<ID> contactID= new Set<ID> ();
        for(Contact con : conList){
            contactID.add(con.Id);
        }
        list<CampaignMember> cm= TestHelper.createCampaignMember(u.Id, cohort[0].id, camp[0].Id,contactID );
        insert cm;
        
        list<CampaignMember> tmpCM= new List<CampaignMember>();
        tmpCM=[SELECT ID,contactID,cohort__c,CampaignID FROM CampaignMember WHERE Cohort__c=:cohort[0].ID AND CampaignID=:camp[0].Id ];
        
        list<Round__c> rList= TestHelper.createRounds(tmpCM[0].Cohort__c, tmpCM[0].CampaignId, 4); 
        insert rList;
        
        
        Set<ID>roundID= new Set<ID>();
        for(Round__c r:rList){
            roundID.add(r.Id);
        }
            
        Test.startTest();
            System.runAs(u){
                
                // confirming can add tasks
                list<Task> taskList = new list<Task>();
                boolean callbackAdded = false;
                for(ID conID:contactID){
                Task newtask= new Task( whatId= rlist[3].id,
                                     whoId=conID,
                                     Subject='MonTRACK Call');
                                     if(!callbackAdded){
                                        newTask.Status = 'Call Back Requested by Student/Other';
                                        newTask.Call_Back_Date_Time__c = datetime.now().addHours(1);
                                        callbackAdded = true;
                                     }
                    taskList.add(newtask);
                }
                insert taskList;
                List<Task> task=[Select Id, WhatID FROM Task where WhatID =:rlist[3].id];
                
                
         
                 PageReference ref = Page.mt_main;
                 Test.setCurrentPage(ref);
                 mt_mainControllerCC montrack = new mt_mainControllerCC();
                 
                 List<selectOption> cOptions = montrack.cohortOptions;
                 montrack.cohort = cohort[0].id;
                 List<selectOption> rOptions = montrack.roundOptions;
                 montrack.round = rList[3].id;
                 List<selectOption> uOptions = montrack.ssaUserOptions;
                 montrack.ssaUser = u.id;
                 montrack.retrieveCalls();
                 
                 string msg = montrack.nextCallbackMessage;
                 
                 system.assertEquals(10,montrack.taskDetailList.size());    // expect one task for each of the 10 students enrolled to montrack
                 // we have list, so simulate selection from list 
                 id tskId = montrack.taskDetailList[0].taskId;
                 id conId = montrack.taskDetailList[0].contactId;
                 
                 apexpages.currentpage().getparameters().put('tId',tskId);
                 apexpages.currentpage().getparameters().put('cId',conId);
                 montrack.taskClicked();
                 
                 taskDetail td = montrack.tdetail; // simulate getter by VF page
                 montrack.testRoundTasks = montrack.otherRounds; // simulate get by VF page 
                 montrack.testTaskHistory = montrack.taskHistories; // simulate get by VF page
                 
                 // confirm input fields 
                 system.assertEquals('Not Started',montrack.currenttask.status);
                 
                 // test the save call validation
                 montrack.resetChildObjects(); // simulate onchange action and then save
                 montrack.currenttask.status = 'Not Started';
                 //montrack.currentTask.Call_Back_Date_Time__c= System.Now();                
                 montrack.saveCall();
                 system.assertEquals('msg2',montrack.errorMsg); // should have prevented save
                 
                 boolean b=montrack.renderTaskTable;               
                 mt_mainControllerCC.roundTask rt=new mt_mainControllerCC.roundTask();
                 rt.cohort=null;
                 rt.round=null;
                 rt.task=null;
                 rt.SSAName=null;
                 rt.createdDate=null;
                 montrack.editOnlyMode=true;
                 
                 montrack.resetChildObjects(); // simulate onchange action and then save
                 montrack.currenttask.status = 'Call Back Requested by Student/Other';
                 //montrack.currentTask.Call_Back_Date_Time__c= System.Now();                
                 montrack.saveCall();
                 system.assertEquals('msg3',montrack.errorMsg); // should have prevented save
                 montrack.currenttask.status = 'No Answer';
                 montrack.resetChildObjects(); // simulate onchange action and then save
                 montrack.currenttask.status = 'No Answer';
                 montrack.currentContact.MonTrack_Opt_Out__c = true;
                 //montrack.currentTask.Call_Back_Date_Time__c= System.Now();                
                 montrack.saveCall();
                 system.assertEquals('msg4',montrack.errorMsg); // should have prevented save
                 
                 montrack.resetChildObjects(); // simulate onchange action and then save
                 montrack.currenttask.status = 'No Answer';
                 montrack.currentContact.MonTrack_Opt_Out__c = true;
                 montrack.currentContact.MonTrack_Opt_Out_Reason__c='Reason'; 
                 montrack.saveCall();
                 
                 // is first call, so save with a not completed result
                 montrack.resetChildObjects(); // simulate onchange action and then save
                 montrack.currenttask.status = 'No Answer';
                 montrack.saveCall();
                 
                 // pull up same again - confirm is now onto second call attempt
                 apexpages.currentpage().getparameters().put('tId',tskId);
                 apexpages.currentpage().getparameters().put('cId',conId);
                 montrack.taskClicked();
                 
                 // register second call attempt without topic and referral
                 montrack.resetChildObjects(); // simulate onchange action and then save
                 montrack.currenttask.status = 'Completed';
                 montrack.currentTask.Reaction_to_Call__c = 'Well Received';
                 montrack.currentTask.Duration_mins__c = '5';
                 montrack.currentTask.Call_Back_Date_Time__c= System.Now();                
                 montrack.saveCall();
                 system.assertEquals('msg0',montrack.errorMsg);  // expect call not to have been saved
                 
                 
                               
                 id tmpId = montrack.currentTask.id; // store this for delete action later in test method
                 
                 // now add a topic and referral, then try to save as completed again
                 
                 montrack.topic.type__c = 'Montrack';
                 montrack.topic.description__c = 'Academic - Exam timetable';
                 montrack.saveTopicRecord();
                 system.assertEquals(1,[ select count() from topic__c where round__c =:montrack.round and student__c =:montrack.contactId]); // confirm insert success
                 
                 montrack.referral.referral__c = 'Childcare';
                 montrack.saveReferralRecord();
                 system.assertEquals(1,[select count() from referrals__c where round__c =:montrack.round and student__c =:montrack.contactId]); // confirm insert success
                 
                 montrack.saveCall(); // expect a successful save this time
                 montrack.clearContextStudent(); // cover off, and going to reset in next step
                 
                 // having saved successfully, now try to save over the top of the completed task
                 apexpages.currentpage().getparameters().put('tId',tskId);
                 apexpages.currentpage().getparameters().put('cId',conId);
                 montrack.taskClicked();                 
                 montrack.saveCall();
                 system.assertEquals('msg1',montrack.errorMsg);
                 
                 montrack.onChangeRefreshList(); // just to run the logic
                 
                 // test delete option
                 
                 montrack.deleteId = tmpId;
                 montrack.deleteTask(); // attempt to delete task added 
                 
                                 
                 // now change cohort and round vals to cover the reset functions
                 montrack.resetRoundAndUser(); // this called on cohort picklist change
                 montrack.cohort = cohort[0].id;
                 montrack.resetUser();
           }           
       Test.stopTest();
    }
    
        static testMethod void throughToNoResultScenario() {
        //create user
        User u= TestHelper.ssaUser();
        //create account
        List<Account> acct= TestHelper.createStudent(10);
        insert acct;
        system.debug('######acct'+acct);
        List<Contact> conList= TestHelper.createStudentContacts(10, acct);
        insert conList;
        Set<ID>accountID = new Set<ID>();
        for(Account a:acct){
            accountID.add(a.ID);
        }
        system.debug('######conList'+conList);
        //create Campaign
        List<Campaign> camp=  TestHelper.createCampaign(1);
        insert camp;
        system.debug('######'+camp);
        //create Cohort
        List<Cohort__c> cohort = TestHelper.createCohort(2);
        insert cohort;
        system.debug('######'+cohort);
        set<ID> contactID= new Set<ID> ();
        for(Contact con:conList){
            contactID.add(con.Id);
        }
        system.debug('######contactID'+contactID);
        list<CampaignMember> cm= TestHelper.createCampaignMember(u.Id, cohort[0].id, camp[0].Id,contactID );
        insert cm;
        system.debug('######'+cm);
        list<CampaignMember> tmpCM= new List<CampaignMember>();
        tmpCM=[SELECT ID,contactID,cohort__c,CampaignID FROM CampaignMember WHERE Cohort__c=:cohort[0].ID AND CampaignID=:camp[0].Id ];
        system.debug('######'+tmpCM);
        list<Round__c> rList= TestHelper.createRounds(tmpCM[0].Cohort__c, tmpCM[0].CampaignId, 4); 
        insert rList;
        
        
        Set<ID>roundID= new Set<ID>();
        for(Round__c r:rList){
            roundID.add(r.Id);
        }
            
        Test.startTest();
            System.runAs(u){
                
                // confirming can add tasks
                list<Task> taskList = new list<Task>();
                for(ID conID:contactID){
                Task newtask= new Task( whatId= rlist[3].id,
                                     whoId=conID,
                                     Subject='MonTRACK Call');
                    taskList.add(newtask);
                }
                insert taskList;
                List<Task> task=[Select Id, WhatID FROM Task where WhatID =:rlist[3].id];
                
                
         
                 PageReference ref = Page.mt_main;
                 Test.setCurrentPage(ref);
                 mt_mainControllerCC montrack = new mt_mainControllerCC();
                 
                 List<selectOption> cOptions = montrack.cohortOptions;
                 montrack.cohort = cohort[0].id;
                 List<selectOption> rOptions = montrack.roundOptions;
                 montrack.round = rList[3].id;
                 List<selectOption> uOptions = montrack.ssaUserOptions;
                 montrack.ssaUser = u.id;
                 montrack.retrieveCalls();
                 system.assertEquals(10,montrack.taskDetailList.size());    // expect one task for each of the 10 students enrolled to montrack
                 // we have list, so simulate selection from list 
                 id tskId = montrack.taskDetailList[0].taskId;
                 id conId = montrack.taskDetailList[0].contactId;
                 
                 apexpages.currentpage().getparameters().put('tId',tskId);
                 apexpages.currentpage().getparameters().put('cId',conId);
                 montrack.taskClicked();
                 
                 // confirm input fields 
                 system.assertEquals('Not Started',montrack.currenttask.status);
                 
                 // is first call, so save with a not completed result
                 montrack.resetChildObjects(); // simulate onchange action and then save
                 montrack.currenttask.status = 'No Answer';
                 montrack.saveCall();
                 
                 // pull up same again - confirm is now onto second result
                 apexpages.currentpage().getparameters().put('tId',tskId);
                 apexpages.currentpage().getparameters().put('cId',conId);
                 montrack.taskClicked();
                 system.assertEquals('First Attempt',montrack.roundTask.Call_Attempt__c);
                 
                 // register second call attempt and add a topic and referral whilst doing so
                 montrack.resetChildObjects(); // simulate onchange action and then save
                 montrack.currenttask.status = 'No Answer';
                 
                 montrack.topic.type__c = 'Montrack';
                 montrack.topic.description__c = 'Academic - Exam timetable';
                 montrack.saveTopicRecord();
                 system.assertEquals(1,[ select count() from topic__c where round__c =:montrack.round and student__c =:montrack.contactId]); // confirm insert success
                 
                 montrack.referral.referral__c = 'Childcare';
                 montrack.saveReferralRecord();
                 system.assertEquals(1,[select count() from referrals__c where round__c =:montrack.round and student__c =:montrack.contactId]); // confirm insert success
                 
                 
                 // now also confirm delete function for newly inserted topic
                 apexpages.currentPage().getParameters().put('tId',montrack.topic.id);
                 montrack.deleteTopicRecord();
                 system.assertEquals(0,[select count() from topic__c where student__c =:montrack.ssaUser and round__c =:montrack.round]);
                 
                 // and confirm referral can be deleted
                 apexpages.currentPage().getParameters().put('rId',montrack.referral.id);
                 montrack.deleteReferralRecord();
                 system.assertEquals(0,[select count() from referrals__c where student__c =:montrack.ssaUser and round__c =:montrack.round]);
                 
                 
                 montrack.saveCall();
                 
                 // pull up same again - confirm is onto third call attempt
                 apexpages.currentpage().getparameters().put('tId',tskId);
                 apexpages.currentpage().getparameters().put('cId',conId);
                 montrack.taskClicked();
                 system.assertEquals('Second Attempt',montrack.roundTask.Call_Attempt__c);
                 
                 // register third attempt
                 montrack.resetChildObjects(); // simulate onchange action and then save
                 montrack.currenttask.status = 'No Answer';
                 montrack.saveCall();
                 
                 // pull up same and confirm can no longer log calls
                 apexpages.currentpage().getparameters().put('tId',tskId);
                 apexpages.currentpage().getparameters().put('cId',conId);
                 montrack.taskClicked();
                 system.assertEquals('Third Attempt',montrack.roundTask.Call_Attempt__c);
                 system.assertEquals('Third Attempt made. No more call attempts possible.',montrack.callAttemptNote);
                 
                 // register third attempt
                 montrack.resetChildObjects(); // simulate onchange action and then save
                 montrack.currenttask.status = 'No Answer';
                 montrack.saveCall();
                 
                 // pull up same and confirm can no longer log calls
                 apexpages.currentpage().getparameters().put('tId',tskId);
                 apexpages.currentpage().getparameters().put('cId',conId);
                 montrack.taskClicked();
                 
                 
           }           
       Test.stopTest();
    }
        
         
}