src/objects/Campaign.object
<CustomObject>
    <recordTypes>
        <fullName>MonTrack</fullName>
        <active>true</active>
        <label>MonTrack</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Cohort__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for MonTRACK functionality; captures the cohort to which a student belongs</description>
        <label>Cohort</label>
        <referenceTo>Cohort__c</referenceTo>
        <relationshipLabel>Campaign Members</relationshipLabel>
        <relationshipName>Campaign_Members</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Cohort__c.object
<CustomObject>
    <description>Describes a group of students within MonTRACK context.</description>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Round__c.object
<CustomObject>
    <description>This object is used to capture the detail of a MonTRACK call round</description>
    <fields>
        <fullName>Cohort__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Links to the related cohort</description>
        <label>Cohort</label>
        <referenceTo>Cohort__c</referenceTo>
        <relationshipLabel>Rounds</relationshipLabel>
        <relationshipName>Rounds</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Round</label>
    <nameField>
        <displayFormat>RND-{00000}</displayFormat>
        <label>Round Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>MonTrack</fullName>
        <active>true</active>
        <label>MonTrack</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CampaignMemberServices.cls
/**
 * Services class to provide CampaignMember sObject centric logical support
 * 
 * @author Carl Vescovi, PwC
 * 
 */


public class CampaignMemberServices {

	
	/**
	* MONTRACK specific logic
	* <p>this class removes tasks related to a now redundant cohort if a montrack campaign member changes cohorts
	* 
	*/
	
	
	
		public class manageChangesOfCohort implements Triggers.Handler {
			
			public void run(){
				
			  List <campaignmember> cmList = new list<campaignmember>();
	          set<id> cohortSet = new set<id>();
	          set<id> contactIds = new set<id>();
		          
	          for(campaignmember cm : (List<CampaignMember>)Trigger.new){
	            
	            campaignmember oldValue = (CampaignMember)Trigger.oldMap.get(cm.id);
	            
	            if(oldValue.Cohort__c != null && cm.Cohort__c != null){
	              if(cm.Cohort__c != oldValue.Cohort__c){
	                  cmList.add(cm);
	                  cohortSet.add(oldValue.cohort__c);
	                  contactIds.add(cm.contactId);
	              }
	            }
	          }
	        
	          // get all the round records for all the changing cohorts
	          
	          if(!cohortSet.isEmpty()){ // this condition handles that this is only done for Montrack campaigns
		          
		          list<Round__c> roundIds = new list<Round__c>([select id from Round__c where cohort__c in: cohortSet]);
		          
		          if(!roundIds.isEmpty()){
			          for(List<task> tasksToDelete : [select id, whoid, whatid from Task where whoid in:contactIds AND 
			                        whatid in: roundIds AND Subject='MonTRACK Call' AND status ='Not Started']){ 
		          
		          	  		delete tasksToDelete; 
			          }
		          }
	      	  }
		           
	        
			}
		}
    
}