src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Course__c.Original_ID__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Linked Enquiries</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Managing_Faculty__c</fullName>
        <description>copied over from REST API result</description>
        <label>Managing Faculty</label>
        <picklist>
            <controllingField>Enquiry_Type__c</controllingField>
            <picklistValues>
                <fullName>Art, Design and Architecture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business and Economics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Law</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medicine, Nursing and Health Sciences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monash College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monash Short course Centre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pharmacy and Pharmaceutical Sciences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Pathways</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <description>used to store data about Monash offerings</description>
    <fields>
        <fullName>Course_Description__c</fullName>
        <externalId>true</externalId>
        <label>Course Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Depreciated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if checked, then the course is no longer offered. This field is used to filter what is available from the &apos;Add Interest&apos; action on enquiry.</description>
        <label>Depreciated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Managing_Faculty__c</fullName>
        <label>Managing Faculty</label>
        <picklist>
            <picklistValues>
                <fullName>a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty of Art, Design &amp; Architecture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty of Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty of Business &amp; Economics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty of Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty of Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty of Information Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty of Law</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty of Medicine, Nursing &amp; Health Sciences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty of Pharmacy &amp; Pharmaceutical Sciences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty of Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monash College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monash Injury Research Institute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monash University Foundation Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CourseServices.cls
/*
 * A services class specific to Course__c sObject
 * @author PwC
 * 
 */
public class CourseServices {
    
	/** returns a map of course information that is indexed by course code */
    
    public static Map<String,Course__c> CourseInfoByName {
        get{
            if(CourseInfoByName == null){
                CourseInfoByName = new Map<String,Course__c>();
                for(List<Course__c> courses: [select id,
                                               name,
                                               Course_Description__c
                                       		   from Course__c limit 2000]){
                     for(Course__c course : courses) CourseInfoByName.put(course.name, course);
                }
            }
            return CourseInfoByName;
        }
        private set;
    }
    
    /**
     * checks for existence of a course code in course table, and if not there 
     * add a new course record.  This addresses the issue of application records being
     * retrieved that there is no course record in crm for, which in turn
     * prevents closure of the enquiry.
     */
    
    public static void checkForAndAddCourseRecords(List<API_ApplicantCourse> applications){
        Set<string> courseCodes = new Set<string>();
        for(API_applicantCourse application : applications) courseCodes.add(application.courseCd);
        Map<string,course__c> courses = new Map<string,course__c>();
        for(course__c course : [ select id,name from course__c where name in :courseCodes]) courses.put(course.name, course);
        list<course__c> newCourses = new list<course__c>();
       
        for(API_ApplicantCourse application : applications){
            // need to add a course record if it doesnt exist in case service console user wants to link to it
            if(!courses.containsKey(application.courseCd)) 
                newCourses.add(new course__c(name = application.courseCd, 
                                             Managing_Faculty__c = application.managingFaculty,
                                             Depreciated__c = true)); // approved assumption is that we're adding old courses
        }
        
        // if we have new course records then insert them
        try{
            insert newCourses;
        } catch (exception ex){ Exlog.write('DML error', 'CourseServices', 'checkForAndAddCourseRecords', ex.getMessage()); }
        
    }
}