src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Course__c.Original_ID__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Linked Enquiries</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enquiry_Type__c</fullName>
        <description>Captures the nature of the enquiry (i.e., Future vs Current course)</description>
        <label>Enquiry Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contact Centre Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolment Extension​</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>How To Apply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leave Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Milestone Management (Progress Management)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monash Doctoral Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Past Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Researcher Development​</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research Student Enrolment​</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>​S​cholarships​</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thesis Submission​</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Person_ID_unique__c</fullName>
        <description>text field that stores person Id, and used by external systems to match to</description>
        <externalId>true</externalId>
        <label>Person ID (text)</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <description>used to store data about Monash offerings</description>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Enquiry_Interest__c.object
<CustomObject>
    <description>stores one or more interests registered against an Enquiry</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>all enquiry interests are derived from a case record</description>
        <label>Enquiry</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Enquiry Interests</relationshipLabel>
        <relationshipName>Enquiry_Interests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>if person is interested in a specific course, this field links to that course record.</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Course__c.Depreciated__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Enquiry Interests</relationshipLabel>
        <relationshipName>Enquiry_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enquiry Interests</relationshipLabel>
        <relationshipName>Enquiry_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enquiry Interest</label>
    <nameField>
        <displayFormat>INT-{000000}</displayFormat>
        <label>Enquiry Interest Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiry Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person_Note__c.object
<CustomObject>
    <description>Subset of notes from SMS, used to id students or authorised significant others</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Person Notes</relationshipLabel>
        <relationshipName>Person_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Important__c</fullName>
        <defaultValue>true</defaultValue>
        <description>if checked, then this will drive the console component to set notes notification button to red with white text</description>
        <inlineHelpText>if checked, then this will drive the console component to set notes notification button to red with white text</inlineHelpText>
        <label>Important</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <controllingField>Special_Care_Reason__c</controllingField>
            <picklistValues>
                <fullName>SPECIAL CARE</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person Note</label>
    <nameField>
        <label>Person Note Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Person Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Console_components_CE_Test.cls
/** test coverage for Console_components_CE custom controller extension 
 * @author PwC
 */
@isTest
private class Console_components_CE_Test {

    @testSetup 
    static void setupTestData(){
    	// if test data required, establish here	
    	
        List<contact> contacts = TestHelper.createOrphanContactRecords(10);
        integer offset = 1;
        for(contact c : contacts) { 
            c.birthdate = date.newInstance(1975,1,1);
            c.Person_Id_unique__c = String.valueOf(12345+offset);
        	offset++;
        }
        insert contacts;
        
        system.assertNotEquals(null, contacts[0].id,'contacts didnt insert as expected');
        
        // add some person notes
        List<Person_Note__c> notes = new List<Person_note__c>();
        for(contact c : contacts) notes.add(new Person_note__c(contact__c = c.id, type__c = 'type', important__c = true, notes__c = 'test note'));
        insert notes;
        
        system.assertNotEquals(null, notes[0].id,'notes didnt insert as expected');
        
        List<Case> cases = TestHelper.webToCaseForms(1);
        cases[0].contactId = contacts[0].id;
        cases[0].Enquiry_Type__c = CaseServices.CURRENT_COURSE;
    	insert cases;
        
        system.assertNotEquals(null, cases[0].id,'cases didnt insert as expected');
        
        // append some enquiry interests
        List<course__c> courses = TestHelper.createCourses(2);
        insert courses;
        
        system.assertNotEquals(null, courses[0].id,'courses didnt insert as expected');
        
        List<Enquiry_Interest__c> interests = new List<Enquiry_Interest__c>();
        for(contact c : contacts){
            for(course__c course : courses){
                for(case cse : cases)
                    interests.add(new Enquiry_Interest__c(course__c = course.id, person__c = c.id, case__c = cse.id));
            }
        }
        insert interests;
        
        system.assertNotEquals(null, interests[0].id,'interests didnt insert as expected');
    }
    
    
    static testMethod void populateListsTest(){
        
        PageReference pg = Page.Console_tabbedLists_v2;
        Test.setCurrentPage(pg);
        
        Case cse = [select id from case limit 1];
        system.assertNotEquals(null, cse.id,'case didnt exist as expected');
        
        ApexPages.StandardController stdCase = new ApexPages.StandardController(cse);
        
        Console_components_CE con = new Console_components_CE(stdCase);
        
		string fdt = con.formattedDateTime;
		con.checkForEncumbrances();
        con.refreshLists();
        
        system.assert(!con.personNotes.isEmpty());
        
    }
    
    
    static testMethod void otherTests(){
        
        PageReference pg = Page.Console_tabbedLists_v2;
        Test.setCurrentPage(pg);
        
        Case cse = [select id, contactId, Enquiry_Type__c from case limit 1];
        ApexPages.StandardController stdCase = new ApexPages.StandardController(cse);
        
        Console_components_CE con = new Console_components_CE(stdCase);
        
		Test.startTest();
        	con.tab = '';
        	con.refreshLists();
        	system.assertEquals('1', con.tab,'tab not set to what it should be');
        	
        	
        	
        	List<SelectOption> options = con.casetypes;
        	system.assertEquals(false, options.isEmpty(),'options should not be empty');
        
        	
        Test.stopTest();
    }
    
    
}