src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Course__c.Original_ID__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Linked Enquiries</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <description>used to store data about Monash offerings</description>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Enquiry_Interest__c.object
<CustomObject>
    <description>stores one or more interests registered against an Enquiry</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>all enquiry interests are derived from a case record</description>
        <label>Enquiry</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Enquiry Interests</relationshipLabel>
        <relationshipName>Enquiry_Interests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>if person is interested in a specific course, this field links to that course record.</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Course__c.Depreciated__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Enquiry Interests</relationshipLabel>
        <relationshipName>Enquiry_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enquiry Interests</relationshipLabel>
        <relationshipName>Enquiry_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enquiry Interest</label>
    <nameField>
        <displayFormat>INT-{000000}</displayFormat>
        <label>Enquiry Interest Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiry Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EnquiryInterestServices_Test.cls
/**
 * This class contains unit tests for validating the behavior of EnquiryInterestServices methods
 * these methods are part of the testing framework implemented throughout UniCRM
 * 
 */
@isTest
private class EnquiryInterestServices_Test {

    // confirm that on insert, a new enquiry interest is linked to both case and person
    
    static testMethod void verifyMappingOfInterestToPerson(){
        
        // UI driven, so small test data sets ok
        
        List<Contact> testContacts = TestHelper.createStudentContacts(1, null);
	    insert testContacts;
        
        List<Case> webToCaseForms = TestHelper.webToCaseForms(20);
	    for(integer index = 0; index < webToCaseForms.size(); index++){
            webToCaseForms[index].contactId = testContacts[0].Id;
        } 
        
        // create a course
        Course__c course = new Course__c(name = '0001');
        insert course;
        
        Test.startTest();
	        
	        insert webToCaseForms; // these are linked to contacts
        	
        	List<Enquiry_Interest__c> enquiries = new List<Enquiry_Interest__c>();
        	for(case webCase : webToCaseForms){
           	 	enquiries.add(new Enquiry_Interest__c(Case__c = webCase.id,
                                                  Course__c = course.id));
                          
        	}
        
        	insert enquiries;
                          
            system.assertEquals(0,
                               [select count() from Enquiry_Interest__c where Person__c = null],
                               'expected contact fields to be populated');    
        
        	for(case c : webToCaseForms) c.Status = 'Closed';
        	update webToCaseForms;
        
        try {
        	delete enquiries;
            system.assertNotEquals(1,0,'should not have permitted deletion of interests on closed cases');
        } catch (exception ex){
            
        }
        
        for(case c : webToCaseForms) c.Status = 'Open';
        update webToCaseForms;
        
        try {
        	delete enquiries;
            
        } catch (exception ex){
            system.assertNotEquals(1,0,'should have permitted deletion of interests on closed cases');
        }
        
        
        Test.stopTest();
    }
    
}