src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>custom last name field used in global action that service console leverages for new contact.</description>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact_to_Task_Field_Mapping__mdt.object
<CustomObject>
    <description>defines mappings that enable copying of information from a Task &apos;who&apos; (Contact) to the task record itself, when the task is of a specific record type. This enables some reporting not possible without information being copied to the activity record itself, such as for MonTrack reporting purposes.</description>
    <fields>
        <fullName>Contact_field_API_name__c</fullName>
        <description>field on contact to be copied</description>
        <inlineHelpText>API name (not label) of Contact field to be copied over to Task record</inlineHelpText>
        <label>Contact field API name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Record_Type__c</fullName>
        <description>Record type of Task record that should use this mapping. Allows custom metadata to map different fields based on record type of the Task record itself.</description>
        <inlineHelpText>Record type (API Name not label ) of Task record that should use this mapping. Allows custom metadata to map different fields based on record type of the Task record itself.</inlineHelpText>
        <label>Task Record Type API Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_field_API_name__c</fullName>
        <description>API name (not label) of field on Task record that Contact field will be copied to</description>
        <inlineHelpText>API name (not label) of field on Task record that Contact field will be copied to</inlineHelpText>
        <label>Task field API name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Contact to Task Field Mapping</label>
    <pluralLabel>Contact to Task Field  Mappings</pluralLabel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>MonTrack</fullName>
        <active>true</active>
        <label>MonTrack</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TaskServices_Test.cls
/**
 * This class contains unit tests for validating the behavior of TaskServices methods
 * these methods are part of the testing framework implemented throughout UniCRM
 * 
 */
@isTest
private class TaskServices_Test {
	
    static testMethod void testMapping(){
        List<Contact_to_Task_Field_Mapping__mdt> fieldMappings = 
                new List<Contact_to_Task_Field_Mapping__mdt>([ SELECT Id, 
                                                                      Contact_field_API_name__c, 
                                                                      Task_field_API_name__c,
                                                              		  Task_Record_Type__c
            														  FROM Contact_to_Task_Field_Mapping__mdt 
                                                             		  where Task_Record_Type__c = 'Montrack' and
                                                             		  Contact_field_API_name__c = 'LastName']);
        system.assert(!fieldMappings.isEmpty(),'No field mappings to test with');
        
        List<Contact> testContacts = TestHelper.createStudentContacts(1, null);
        insert testContacts;
        
        id taskRecordType = [select id from RecordType where SObjectType = 'Task' and DeveloperName = 'Montrack' limit 1].id;
        
        Task t = new task(recordtypeId = taskRecordType,
                         subject = 'test',
                         whoId = testContacts[0].id,
                         last_name__c = '');
        insert t;
        system.assertEquals(testContacts[0].lastname,
                           [select last_name__c from task where id =:t.id limit 1].last_name__c,
                           'last name didnt map to task as expected');
        
        
        TaskServices.updateTaskRecords(new list<task>{ t });
        
        TaskServices.deleteTaskRecords(new list<task>{ t });
    }
}