src/objects/Enquiry_Interest__c.object
<CustomObject>
    <description>stores one or more interests registered against an Enquiry</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>all enquiry interests are derived from a case record</description>
        <label>Enquiry</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Enquiry Interests</relationshipLabel>
        <relationshipName>Enquiry_Interests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enquiry Interests</relationshipLabel>
        <relationshipName>Enquiry_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enquiry Interest</label>
    <nameField>
        <displayFormat>INT-{000000}</displayFormat>
        <label>Enquiry Interest Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiry Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EnquiryInterestServices.cls
/*
 * A services class specific to Enquiry Interest custom sObject
 * @author PwC
 * 
 */
public with sharing class EnquiryInterestServices {
    
    /**
    * when an interest is created against a case record, also link it to the person the case is linked to 
    * this event happens in console, which is not where we want this additional logic implemented
    */
	    public class linkInterestsToPerson implements Triggers.Handler {
	    	public void run(){
	    		
	    		Set<Id> caseIds = new Set<Id>();
	    		for(Enquiry_Interest__c interest : (List<Enquiry_Interest__c>)Trigger.new){
	    			if(interest.Case__c != null) caseIds.add(interest.Case__c);
	    		}
	    		
	    		Map<id,Case> cases = new Map<id,Case>([select id,
							    								contactId 
							    								from Case 
							    								where contactId != null and id in:caseIds]);
	    		
	    		// now for any enquiry interests that link to a case that has a person linked to it, link
	    		// the enquiry interest directly to the person as well.
	    		
	    		for(Enquiry_Interest__c interest : (List<Enquiry_Interest__c>)Trigger.new){
	    			if(interest.Case__c != null && interest.Person__c == null && cases.containskey(interest.case__c)){
	    				interest.Person__c = cases.get(interest.case__c).contactId;
	    			} 
	    		}
	    		
	    	}
	    	
	    }
    
    /** 
     * prevent deletion of enquiry interest by users when on closed cases, except by system admin users
     */
    public class preventDeletionOnClosedCases implements Triggers.Handler {
        public void run(){
            Set<id> caseIds = new Set<id>();
            for(Enquiry_Interest__c interest : (List<Enquiry_Interest__c>)Trigger.old) caseIds.add(interest.case__c);
            Map<id,case> cases = new Map<id,case>([select id,IsClosed from case where id in:caseIds]);
            for(Enquiry_Interest__c interest : (List<Enquiry_Interest__c>)Trigger.old){
                if(cases.get(interest.case__c).IsClosed) interest.addError('Not permitted to delete enquiry interests from closed cases.');
            }
        }
    }
}