src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Enquiry_Role__c</fullName>
        <description>used by service console user</description>
        <label>Enquiry Role</label>
        <picklist>
            <picklistValues>
                <fullName>Phone &amp; Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Face to Face &amp; Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Set</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>used by my location component for service console</description>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Berwick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caulfield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clayton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gippsland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parkville</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peninsula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Set</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <description>used by service console</description>
        <label>Queue</label>
        <picklist>
            <picklistValues>
                <fullName>Current Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Set</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UserServices_Test.cls
/**
 * This class contains unit tests for validating the behavior of UserServices methods
 * these methods are part of the testing framework implemented throughout UniCRM
 * 
 */
@isTest
private class UserServices_Test {

    static testMethod void testUserInfoClearout(){
        
        User usr = TestHelper.createTestUsers('Base Profile',1)[0];
        usr.Queue__c = 'test';
        usr.Location__c = 'test';
        usr.Enquiry_Role__c = 'test';
        update usr;
        
        System.runAs(usr){
            UserServices.resetMyInformation();
        }
        
        usr = [select id,queue__c,location__c,enquiry_role__c from User where id =:usr.id limit 1];
        
        system.assertEquals(null, usr.queue__c);
        system.assertEquals(null, usr.Location__c);
        system.assertEquals(null, usr.Enquiry_Role__c);
    }
    
}