src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Enquiry_Role__c</fullName>
        <description>used by service console user</description>
        <label>Enquiry Role</label>
        <picklist>
            <picklistValues>
                <fullName>Phone &amp; Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Face to Face &amp; Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Set</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>used by my location component for service console</description>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Berwick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caulfield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clayton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gippsland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parkville</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peninsula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Set</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>My_Information_LastUpdate__c</fullName>
        <description>last time this information updated</description>
        <label>My Information LastUpdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <description>used by service console</description>
        <label>Queue</label>
        <picklist>
            <picklistValues>
                <fullName>Current Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Set</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Console_MyInformation_CCv2_Test.cls
/**
 * Test class for the Console_MyInformation_CCv2 custom controller class.
 * These methods are part of the testing framework implemented throughout UniCRM
 */
@isTest
private class Console_MyInformation_CCv2_Test {

    static testMethod void checkController(){
        
        List<User>  users = TestHelper.createTestUsers('Monash Connect Officer', 1);
        
        Test.setCurrentPage(Page.Console_MyInformation_v2);
        
        System.runAs(users[0]){
            Console_MyInformation_CCv2 con = new Console_MyInformation_CCv2();
            List<selectOption> opts = con.locations;
            con.newUser.Location__c = opts[1].getValue();
            
            opts = con.queues;
            con.newUser.Queue__c = opts[1].getValue();
            
            con.storeInputs();
            system.assertEquals(1,
                                  [select count() from User where My_Information_LastUpdate__c = null and id =:users[0].id],
                                  'User updated with incomplete data');	
            
            opts = con.enquiryroles;
            con.newUser.Enquiry_Role__c = opts[1].getValue();
            con.storeInputs();
            
            system.assertEquals(0,
                                  [select count() from User where My_Information_LastUpdate__c = null and id =:users[0].id],
                                  'User not updated as expected');	
            
        }
        
        
        
    }
    
    
}