src/objects/User.object
<CustomObject>
    <fields>
        <fullName>SSO_AgentId__c</fullName>
        <label>SSO_AgentId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSO_Extension__c</fullName>
        <label>SSO_Extension</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSO_Pwd__c</fullName>
        <label>SSO_Pwd</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SingleSignOn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SingleSignOn</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Apex_UserInfo.cls
global class Apex_UserInfo{

webService static String getCurrUserSSOInfo() {   
                   User u = [SELECT SingleSignOn__c, SSO_AgentId__c, SSO_Pwd__c, SSO_Extension__c FROM User WHERE Id = :UserInfo.getUserId()];
   
                String JSONString = JSON.serialize(u);
       
                return JSONString;
   }
   

webService static Void saveCurrUserSSOInfo(String agentId, String pwd, String extension) {
       User u = new User();       
       u.Id = UserInfo.getUserId();
       
       u.SSO_AgentId__c = agentId;
       u.SSO_Pwd__c = pwd;
       u.SSO_Extension__c = extension;
       
       update u;   
   }



}